{% set version = "0.1.4" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-metalite
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/metalite_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/metalite/metalite_{{ version }}.tar.gz
  sha256: 30f88d56e405adc3f99f8fd23cea622802d160b6ea4a8466099d2c5c6818d6d0

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-glue
    - r-rlang
  run:
    - r-base
    - r-glue
    - r-rlang

test:
  commands:
    - $R -e "library('metalite')"           # [not win]
    - "\"%R%\" -e \"library('metalite')\""  # [win]

about:
  home: https://merck.github.io/metalite/, https://github.com/Merck/metalite
  license: GPL-3.0-only
  summary: A metadata structure for clinical data analysis and reporting based on Analysis Data Model (ADaM) datasets. The package simplifies clinical analysis and reporting tool development by defining standardized inputs, outputs, and workflow. The package can be used to create analysis and reporting planning grid, mock
    table, and validated analysis and reporting results based on consistent inputs.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
